name: Run Bot

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Start bot
        env:
          MUNIFICUS_TOKEN: ${{ secrets.MUNIFICUS_TOKEN }}
          MUNIFICUS_CLIENT: ${{ secrets.MUNIFICUS_CLIENT}}
        run: |
          echo "Booting up bot..."
          node index.js
